# Modkey
#modkey = "Mod4"

# Mousekey
#mousekey = "Mod4"

# Focus Behaviour
focus_behaviour = "ClickTo"
focus_new_windows = true

# Tags
tags = ["1", "2", "3", "4", "5", "6", "7", "8"]

# Tag Behaviour
#disable_current_tag_swap = false

# Layouts
layouts = [
    "MainAndDeck",
    "MainAndVertStack",
    "MainAndHorizontalStack",
    "GridHorizontal",
    "EvenHorizontal",
    "EvenVertical",
    "Fibonacci",
    "CenterMain",
    "CenterMainBalanced",
    "Monocle",
    "RightWiderLeftStack",
    "LeftWiderRightStack",
]

# workspaces
#workspaces = []

# Scratchpads (require a keybind for ToggleScratchPad)
[[scratchpad]]
name = "Kitty"
value = "GLFW_IM_MODULE=ibus kitty"

# Keybind
[[keybind]]
command = "ToggleScratchPad"
value = "GLFW_IM_MODULE=ibus kitty"
modifier = ["modkey"]
key = "t"

[[keybind]]
command = "Execute"
value = "rofi -show run"
modifier = ["modkey"]
key = "p"

[[keybind]]
command = "HardReload"
modifier = ["modkey", "Escape"]
key = "r"

[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "j"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "k"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "j"

[[keybind]]
command = "ToggleFullScreen"
modifier = ["modkey"]
key = "f"

[[keybind]]
command = "CloseWindow"
modifier = ["modkey"]
key = "q"

[[keybind]]
command = "IncreaseMainWidth"
value = "5"
modifier = ["modkey"]
key = "plus"

[[keybind]]
command = "DecreaseMainWidth"
value = "5"
modifier = ["modkey"]
key = "minus"

[[keybind]]
command = "FocusNextTag"
modifier = ["modkey"]
key = "Tab"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey", "Shift"]
key = "Tab"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "F1"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "F2"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "F3"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "F4"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "F5"

[[keybind]]
command = "MoveToTag"
value = "6"
modifier = ["modkey", "Shift"]
key = "F6"

[[keybind]]
command = "MoveToTag"
value = "7"
modifier = ["modkey", "Shift"]
key = "F7"

[[keybind]]
command = "MoveToTag"
value = "8"
modifier = ["modkey", "Shift"]
key = "F8"

[[keybind]]
command = "MoveToTag"
value = "9"
modifier = ["modkey", "Shift"]
key = "F9"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "F1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "F2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "F3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "F4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "F5"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "F6"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "F7"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "F8"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "F9"

[[keybind]]
command = "RotateTag"
modifier = ["modkey"]
key = "z"

[[keybind]]
command = "SwapTags"
modifier = ["modkey"]
key = "w"

[[keybind]]
command = "NextLayout"
modifier = ["modkey", "Control"]
key = "Up"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Control"]
key = "Down"

[[keybind]]
command = "SetLayout"
value = "Monocle"
modifier = ["modkey"]
key = "m"

[[keybind]]
command = "FloatingToTile"
modifier = ["modkey", "Shift"]
key = "t"

[[keybind]]
command = "SetMarginMultiplier"
value = "2.0"
modifier = ["modkey"]
key = "asterisk"

[[keybind]]
command = "SetMarginMultiplier"
value = "0.5"
modifier = ["modkey"]
key = "division"
